from pydantic import BaseModel

class PublisherSummary(BaseModel):
    """
    Natural-language summary generated by the Publisher Agent.
    """
    report: str


class PublicationReport(BaseModel):
    """
    Final publication result returned by the publisher stage.
    """
    overall_score: float
    passed: bool
    pdf_path: str | None
    report: str